# Generated by Django 5.2.3 on 2025-07-03 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
    ]
