# Generated by Django 5.2.3 on 2025-07-07 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_user_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='is_assigned',
            field=models.BooleanField(default=False),
        ),
    ]
