# Generated by Django 5.2.3 on 2025-07-12 18:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_vehicle_created_by_vehicle_created_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driversprofile',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_driverProfile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='driversprofile',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driversprofile',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_driverProfile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='driversprofile',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
